name: Build & Deploy Frontend + Backend PHP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Deploy frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/
          state-name: .ftp-deploy-sync-state-frontend.json
          dangerous-clean-slate: false

      - name: Deploy backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./api/
          server-dir: /public_html/api/
          state-name: .ftp-deploy-sync-state-backend.json
          dangerous-clean-slate: false

      - name: Deploy libs via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          passive: true
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./lib/
          server-dir: /public_html/lib/
          state-name: .ftp-deploy-sync-state-backend.json
          dangerous-clean-slate: false

      # Pushover notification
      - name: Send Pushover Notification
        if: success()
        run: |
          curl -s \
            -F "token=${{ secrets.PUSHOVER_API_TOKEN }}" \
            -F "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            -F "title=Deployment Successful" \
            -F "message=Projekt został pomyślnie wdrożony na serwer." \
            https://api.pushover.net/1/messages.json
